### ISSUE TITLE
Custom validator function

### ISSUE THREAD

**Issue by lplanch** [restuwahyu13/go-playground-converter#4]
Hi, I'm new to golang and I'm trying to register a custom validation (with validator.RegisterValidation), but I can't make it work. 
Could you provide me an example with this code base?

```golang
func GoValidator(s interface{}, config []gpc.ErrorMetaConfig) (interface{}, int) {
	var validate *validator.Validate
	validators := gpc.NewValidator(validate)
	bind := gpc.NewBindValidator(validators)

	errResponse, errCount := bind.BindValidator(s, config)
	return errResponse, errCount
}
```
Thanks!

**Comment by restuwahyu13** [comment]
Thanks your request issue @lplanch , you used lib old version `v0.0.5` for now this lib version `v1.0.2`, for old version you can check this example ![here](https://github.com/restuwahyu13/go-rest-api/blob/main/utils/validator.go)

Install lib like this `go get github.com/restuwahyu13/go-playground-converter@v0.0.5`, can't use -u, because command -u for update lib to latest version

Recommended used latest version, because many improved code and upgraded outdated dependency

**Comment by lplanch** [comment]
@restuwahyu13 thank you for the fast reply!
And could you provide me an example on how to add a custom validation with `RegisterValidation` with the new version of `go-playground-converter`? thanks!

**Comment by restuwahyu13** [comment]
for new version you can used like this, add this in your custom lib file

```go
func GoValidator(s interface{}) (*gpc.FormatError, error) {
 res, err := gpc.Validator(s) // <- pass your struct from param in here

 if err != nil {
   return nil, err
 }

  return res, nil
}

```
